services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - app
  app:
    build: ./node
    image: app
    container_name: app
    tty: true
    volumes:
      - /usr/src/app/node_modules
      - ./node:/usr/src/app
    networks:
      - node-network
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: nodedb
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
