services:
  app:
    build: ./node
    image: victorfreixinho/node-app
    container_name: node-app
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-network
    depends_on:
      - db

  db:
    image: mysql
    container_name: node-db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
